import { Product } from './types/product';

export const sampleProducts: Product[] = [
  {
    name: 'watch',
    slug: 'skmei-watch-man',
    category: 'Watch',
    image: '../images/skmei 1805 p1.png',
    price: 120,
    countInStock: 10,
    brand: 'skmei',
    rating: 4.5,
    numReviews: 10,
    description:
      'Some Skmei watches are equipped with features such as stopwatches, alarms, water resistance, and LED displays. If you have any specific questions about Skmei ...',
  },
  {
    name: 'watch',
    slug: 'skmei-watch-man',
    category: 'Watch',
    image: '../images/olevs 2865 p2.png',
    price: 110,
    countInStock: 10,
    brand: 'skemi',
    rating: 4.8,
    numReviews: 15,
    description:
      'Dial Window Material Type: Coated Glass · Dial Diameter: 39mm/27mm · Case Shape: Round · Band Length: 24cm · Clasp Type: Leather Deployment Bucket · Water Resistance ...',
  },
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/biden 0178 p4.png',
    price: 120,
    countInStock: 10,
    brand: 'olevs',
    rating: 4.5,
    numReviews: 10,
    description:
      'Dial Window Material Type: Coated Glass · Dial Diameter: 39mm/27mm · Case Shape: Round · Band Length: 24cm · Clasp Type: Leather Deployment Bucket · Water Resistance ...',
  },
  {
    name: 'BIDEN Mens Watches ',
    slug: 'watch man',
    category: 'watch',
    image: '../images/biden p5.png',
    price: 120,
    countInStock: 15,
    brand: 'olevs',
    rating: 4.5,
    numReviews: 12,
    description:
      'Dial Window Material Type: Coated Glass · Dial Diameter: 39mm/27mm · Case Shape: Round · Band Length: 24cm · Clasp Type: Leather Deployment Bucket · Water Resistance ...',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../images/olevs p8.png',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../images/p7.png',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality product',
  },
];
